apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - image: postgres:15.1-alpine
          name: postgresql
          env:
            - name: POSTGRES_PASSWORD
              value: developer
            - name: POSTGRES_DB
              value: development
            - name: POSTGRES_USER
              value: developer
          resources:
            limits:
              memory: 128Mi
              cpu: "500m"
