apiVersion: v1
kind: Pod
metadata:
  name: your-app
  labels:
    app: YourApp
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Never
