apiVersion: v1
kind: ConfigMap
metadata:
  name: config-env
data:
  TEST_ENV: test

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: k8s.gcr.io/busybox
      command: ["env"] # print env vars
      envFrom:
        - configMapRef:
            name: test-config
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
