apiVersion: v1
type: Opaque
data:
  username: YWRtaW4= # admin
  password: MTIzNDU= # 12345
kind: Secret
metadata:
  name: mysecret
  namespace: default

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: ["env"]
      envFrom:
        - secretRef:
            name: mysecret
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
